name: hatchet-starter

include:
  - packages/hatchet/compose.hatchet.yaml

services:
  worker:
    restart: unless-stopped
    build:
      dockerfile: docker/Dockerfile
      context: packages/worker
      target: dev
    cpus: '1'
    mem_limit: 512mb
    environment:
      - HATCHET_CLIENT_TLS_STRATEGY=none
      - HATCHET_CLIENT_WORKER_HEALTHCHECK_ENABLED=True
      - HATCHET_CLIENT_WORKER_HEALTHCHECK_PORT=8002
      - X_HATCHET_CLIENT_SECRETS_DIR=/opt/hatchet/secrets
    develop:
      watch:
        - action: sync+restart
          x-initialSync: true
          path: ./packages/worker/worker
          target: /app/worker
        - action: rebuild
          path: ./packages/worker/docker
        - action: rebuild
          path: ./packages/worker/uv.lock
    volumes:
      - hatchet-secrets:/opt/hatchet/secrets:ro
    depends_on:
      hatchet:
        condition: service_healthy
        restart: true
