services:
  hatchet-init:
    cpus: '0.250'
    mem_limit: 512mb
    build:
      dockerfile: docker/Dockerfile
      target: dev
      args:
        ## NOTE: below can be used to override Dockerfile build defaults
        - LITE_FRONTEND_PORT=8180
        - LITE_RUNTIME_PORT=8880
        - SERVER_GRPC_PORT=7070
        - SERVER_PORT=8080
    command:
      - '/init-local.sh'
    environment:
      ##
      ## -- begin Hatchet environment variables --
      ##
      - SERVER_GRPC_BROADCAST_ADDRESS=hatchet:7070
      - SERVER_URL=http://hatchet:8080
      ## NOTE: these come from `.env`
      - ADMIN_PASSWORD
      - DATABASE_POSTGRES_HOST
      - DATABASE_POSTGRES_PORT
      - DATABASE_POSTGRES_USERNAME
      - DATABASE_POSTGRES_PASSWORD
      - DATABASE_POSTGRES_DB_NAME
      - SERVER_AUTH_COOKIE_SECRETS
      - SERVER_ENCRYPTION_MASTER_KEYSET
      - SERVER_ENCRYPTION_JWT_PUBLIC_KEYSET
      - SERVER_ENCRYPTION_JWT_PRIVATE_KEYSET
      ## NOTE: these are optional overrides
      # - DATABASE_LOGGER_LEVEL=debug
      - DATABASE_LOGGER_FORMAT=console
      # - SERVER_LOGGER_LEVEL=debug
      - SERVER_LOGGER_FORMAT=console
      ##
      ## -- ^ end Hatchet environment variables ^ --
      ##
      - RELEASE_COMMAND=1
      - X_HATCHET_CLIENT_SECRETS_DIR=/opt/hatchet/secrets
    develop:
      watch:
        - action: sync+restart
          x-initialSync: true
          path: ./config
          target: /opt/hatchet/config
        - action: rebuild
          path: ./docker
    volumes:
      - hatchet-secrets:/opt/hatchet/secrets:rw
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  hatchet:
    extends:
      service: hatchet-init
    command: !reset null
    restart: unless-stopped
    environment:
      - RELEASE_COMMAND=0
    volumes: !reset []
    ports:
      - 47069-47070:7070 ## Engine gRPC
      - 48079-48080:8080 ## API
      - 48179-48181:8180 ## UI
      - 48879-48880:8880 ## Lite reverse proxy
    depends_on:
      hatchet-init:
        condition: service_completed_successfully
        restart: true

  postgres:
    image: postgres:15.6
    command: postgres -c 'max_connections=200'
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_POSTGRES_DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DATABASE_POSTGRES_DB_NAME} -U ${DATABASE_POSTGRES_USERNAME}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - hatchet-postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  hatchet-postgres: ~
  hatchet-secrets: ~
